export const ORDER_ITEM_REQUEST = "ORDER_ITEM_REQUEST"
export const ORDER_ITEM_SUCCESS = "ORDER_ITEM_SUCCESS"
export const ORDER_ITEM_FAIL = "ORDER_ITEM_FAIL"

export const MY_ORDER_ITEM_REQUEST = "MY_ORDER_ITEM_REQUEST"
export const MY_ORDER_ITEM_SUCCESS = "MY_ORDER_ITEM_SUCCESS"
export const MY_ORDER_ITEM_FAIL = "MY_ORDER_ITEM_FAIL"

export const ORDER_DETAIL_REQUEST = "ORDER_DETAIL_REQUEST"
export const ORDER_DETAIL_SUCCESS ="ORDER_DETAIL_SUCCESS"
export const ORDER_DETAIL_FAIL = "ORDER_DETAIL_FAIL"

export const CLEAR_ERROR= "CLEAR_ERROR"
